# ==============================================================================
# Role: redis - Handlers
# ==============================================================================

---
- name: Restart redis
  ansible.builtin.command:
    cmd: docker compose restart
    chdir: "{{ redis_install_path }}"
  become: true

- name: Stop redis
  ansible.builtin.command:
    cmd: docker compose down
    chdir: "{{ redis_install_path }}"
  become: true

- name: Update redis
  ansible.builtin.command:
    cmd: docker compose pull && docker compose up -d
    chdir: "{{ redis_install_path }}"
  become: true
