# ==============================================================================
# Role: docmost - Handlers
# ==============================================================================

---
- name: Restart docmost
  ansible.builtin.command:
    cmd: docker compose restart
    chdir: "{{ docmost_install_path }}"
  become: true

- name: Stop docmost
  ansible.builtin.command:
    cmd: docker compose down
    chdir: "{{ docmost_install_path }}"
  become: true

- name: Update docmost
  ansible.builtin.shell:
    cmd: docker compose pull && docker compose up -d
    chdir: "{{ docmost_install_path }}"
  become: true
